---
- name: "Skip config"
  ansible.builtin.meta: end_host
  when:
    - repo_proxy_configure is defined
    - not repo_proxy_configure | bool

- name: Debian tasks
  ansible.builtin.import_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Redhat tasks
  ansible.builtin.import_tasks: setup-redhat.yml
  when: ansible_os_family in ["RedHat", "Rocky", "OracleLinux"]
