---
- name: Debian tasks
  ansible.builtin.import_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Redhat tasks
  ansible.builtin.import_tasks: setup-redhat.yml
  when: ansible_os_family in ["RedHat", "Rocky", "OracleLinux"]
