---
- name: "DEBIAN: Skip config apt-proxy if its himself"
  ansible.builtin.meta: end_host
  when: inventory_hostname == apt_proxy_hostname

- name: "DEBIAN: Check if {{ apt_proxy_file }} exist."
  ansible.builtin.stat:
    path: "{{ apt_proxy_file }}"
  register: proxyfile

- name: "DEBIAN: Check if proxy is set properly"
  ansible.builtin.lineinfile:
    dest: "{{ apt_proxy_file }}"
    line: "Acquire::http::Proxy \"{{ apt_proxy }}\";"
  check_mode: 'yes'
  register: apt_check
  changed_when: false
  when: proxyfile.stat.exists

- name: "DEBIAN: Change Proxy configuration"
  when: not proxyfile.stat.exists or apt_check.changed
  block:
    - name: "DEBIAN: Make sure to remove other proxy configuration"
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf
        state: absent
        regexp: '^Acquire::http(.*)Proxy'

    - name: "DEBIAN: Remove custom proxy files"
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ apt_proxy_remove }}"

    - name: "DEBIAN: Set up new apt-proxy file"
      ansible.builtin.copy:
        dest: "{{ apt_proxy_file }}"
        mode: '0644'
        content: |
          Acquire::http::Proxy "{{ apt_proxy }}";
          Acquire::https::Proxy "{{ apt_proxy }}";

    - name: "DEBIAN: Update repositories cache"
      ansible.builtin.apt:
        update_cache: 'yes'
        cache_valid_time: 86400
      register: apt_result
      retries: 20
      delay: 10
      until: apt_result is success
