---
- name: "REDHAT: Add proxy to yum config"
  ansible.builtin.lineinfile:
    dest: /etc/yum.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - {regexp: "^proxy", line: "proxy={{ yum_proxy }}"}
  when:
    - yum_proxy is defined
    - yum_proxy | length > 0
